export const Users={
    FETCH_USERS :'FETCH_USERS',
    MORE_USERS : 'MORE_USERS',
    SEARCH_USER : 'SEARCH_USER',
    FETCH_GROUP_USERS : 'FETCH_GROUP_USERS',
    ADD_USER : 'ADD_USER',
    DELETE_USER : 'DELETE_USER',
    UPDATE_USER: 'UPDATE_USER'
    
}
export const Group ={
    FETCH_GROUPS :'FETCH_GROUPS', 
    SEARCH_GROUP : 'SEARCH_GROUP',
    ADD_GROUP : 'ADD_GROUP',
    DELETE_GROUP : 'DELETE_GROUP',
    UPDATE_GROUP: 'UPDATE_GROUP',
}

export const Global ={
    HANDLE_LEFT: 'HANDLE_LEFT',
    HANDLE_MODAL: 'HANDLE_MODAL',
    CONTENT_STATS: 'CONTENT_STATS'
}